services:
  - type: web
    name: financial-dashboard
    runtime: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: GOOGLE_DRIVE_FOLDER_ID
        value: 1BeZnlEkXFso4H2KUiUDq1qAKD8gc3XEH
